//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trabajofinal_programacion_avanzada_logistica.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos
    {
        public Gastos()
        {
            this.Solicitudes = new HashSet<Solicitudes>();
        }
    
        public int Id { get; set; }
        public int ProyectoId { get; set; }
        public int UsuarioId { get; set; }
        public decimal Monto { get; set; }
        public string Categoria { get; set; }
        public string Estado { get; set; }

        public string Gasto { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual Proyectos Proyectos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
        public DateTime Fecha { get; internal set; }
        public string Comprobante { get; internal set; }
    }
}
