//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trabajofinal_programacion_avanzada_logistica.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinControlDBEntities : DbContext
    {
        public FinControlDBEntities()
            : base("name=FinControlDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Gastos> Gastos { get; set; }
        public DbSet<Proyectos> Proyectos { get; set; }
        public DbSet<Reportes> Reportes { get; set; }
        public DbSet<Solicitudes> Solicitudes { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
