//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trabajofinal_programacion_avanzada_logistica.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        public Proyectos()
        {
            this.Gastos = new HashSet<Gastos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
    
        public virtual ICollection<Gastos> Gastos { get; set; }
    }
}
