//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trabajofinal_programacion_avanzada_logistica.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reportes
    {
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public string NombreArchivo { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
